# Generated by Django 3.2 on 2021-04-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_accesory_bike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesory',
            options={'verbose_name': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AddField(
            model_name='accesory',
            name='accessory_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
