# Generated by Django 3.2 on 2021-04-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210422_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesory',
            options={'verbose_name': 'Accessorie'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.RemoveField(
            model_name='accesory',
            name='accessory_name',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='model',
        ),
    ]
