# Generated by Django 3.2 on 2021-04-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210422_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accesory',
            new_name='Accessory',
        ),
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='accessory',
            old_name='accesory_type',
            new_name='accessory_type',
        ),
    ]
