# Generated by Django 3.2 on 2021-05-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210426_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
