# Generated by Django 3.2.3 on 2021-05-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210507_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='for_anonymous_user',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='in_order',
        ),
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
