# Generated by Django 3.2.3 on 2021-05-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_customer_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='final_price',
        ),
    ]
