# Generated by Django 3.2.3 on 2021-05-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_cartproduct_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
